backend:
  name: git-gateway
  branch: master

media_folder: "src/assets/img"
public_folder: "/src/assets/img"

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
